# -*- coding: utf-8 -*-
"""yolov8_roboflow_train_with_hyp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OupXLVOGWXs0gwGafpsIdcH7YRYJ8yHm

# 🔍 YOLOv8 + Roboflow + hyp.yaml ile Eğitim

Bu notebook, Roboflow'dan veri indirerek YOLOv8 ile özel veri setinizde eğitim yapar. Ayrıca özel hiperparametre ayarlarını `hyp.yaml` dosyası üzerinden uygular.
"""

#!pip install -q roboflow ultralytics
#!pip install ultralytics
#!pip install roboflow


import torch

device = "cuda" if torch.cuda.is_available() else "CPU"
print(f"Kullanılacak cihaz: {device}")

# 🔧 Gerekli kütüphaneleri kur


from roboflow import Roboflow
rf = Roboflow(api_key="xxxxx")
project = rf.workspace("yoda-uyeu2").project("dogfight")
version = project.version(1)
dataset = version.download("yolov8")

data_yaml_path = f"{dataset.location}/data.yaml"

# ✏️ hyp.yaml dosyasını oluştur
hyp_yaml = """lr0: 0.01
momentum: 0.937
weight_decay: 0.0005
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
mixup: 0.0
"""

with open("hyp.yaml", "w") as f:
    f.write(hyp_yaml)

from ultralytics import YOLO
import yaml

# Hyp.yaml içeriğini oku
with open("hyp.yaml", "r") as f:
    hyp_params = yaml.safe_load(f)

# Modeli başlat
model = YOLO("yolov8s.pt")

# Eğitimi başlat
model.train(
    data=data_yaml_path,
    epochs=100,
    imgsz=640,
    batch=16,
    name="roboflow_custom_model",
    **hyp_params  # hyp dosyasındaki parametreleri buraya geçiriyoruz
)

# 🔍 Test için tahmin
#model = YOLO("runs/detect/roboflow_custom_model/weights/best.pt")

# Örnek görsel ile tahmin (test klasöründen bir görsel yolu girin)
#results = model.predict(source=f"{dataset.location}/test/images", save=True)
